FROM postgres:alpine

# DB initialization now invoked from the application (ATC service) container
# ADD ./db_init.sql /tmp/db_init.sql
# ADD ./additional_db.sh /docker-entrypoint-initdb.d/

# ADD convert /var/local/convert
# ADD test /var/local/test
# ADD migrate /var/local/migrate
# ADD db_init.sql /var/local/db_init.sql

EXPOSE 5432