// Code generated by protoc-gen-go. DO NOT EDIT.
// source: onboarding-demo/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4496b8d0625f272, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

func init() {
	proto.RegisterFile("onboarding-demo/pkg/pb/service.proto", fileDescriptor_a4496b8d0625f272)
}

var fileDescriptor_a4496b8d0625f272 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x55, 0x06, 0x0a, 0x1e, 0x00, 0x65, 0x40, 0xa5, 0x65, 0x40, 0x15, 0x03, 0x12, 0xc4,
	0x96, 0x60, 0x83, 0x09, 0x04, 0x62, 0x04, 0x75, 0x60, 0x60, 0xb3, 0x93, 0xab, 0xb1, 0x48, 0xee,
	0x2c, 0xdb, 0x0d, 0xcd, 0xca, 0x2b, 0xf0, 0x68, 0xbc, 0x02, 0x0f, 0x82, 0x9a, 0x38, 0x55, 0x04,
	0xdd, 0xf2, 0xdf, 0x5d, 0xfe, 0x4f, 0xfa, 0xcc, 0x4e, 0x09, 0x15, 0x49, 0x97, 0x1b, 0xd4, 0x69,
	0x0e, 0x25, 0x09, 0xfb, 0xae, 0x85, 0x55, 0xc2, 0x83, 0xab, 0x4c, 0x06, 0xdc, 0x3a, 0x0a, 0x94,
	0x0c, 0x63, 0x1c, 0x4f, 0x34, 0x91, 0x2e, 0x40, 0x34, 0x63, 0xb5, 0x98, 0x0b, 0x28, 0x6d, 0xa8,
	0xdb, 0xab, 0xf1, 0x71, 0x5c, 0x4a, 0x6b, 0x84, 0x44, 0xa4, 0x20, 0x83, 0x21, 0xf4, 0x71, 0x7b,
	0xab, 0x4d, 0x78, 0x5b, 0x28, 0x9e, 0x51, 0x29, 0x00, 0x2b, 0xaa, 0xad, 0xa3, 0x65, 0xdd, 0x36,
	0x65, 0xa9, 0x06, 0x4c, 0x2b, 0x59, 0x98, 0x5c, 0x06, 0x10, 0xff, 0x3e, 0x62, 0xc5, 0x45, 0xef,
	0xd8, 0x7f, 0x48, 0xad, 0xc1, 0x09, 0xb2, 0x0d, 0x64, 0x03, 0xf0, 0xba, 0x07, 0x34, 0x38, 0x27,
	0x55, 0xd0, 0x92, 0x2c, 0x60, 0x1f, 0xa9, 0xc9, 0x95, 0xeb, 0x8a, 0x55, 0x68, 0xff, 0x9d, 0x9e,
	0xb3, 0xfd, 0x17, 0x70, 0xde, 0x10, 0xce, 0xc0, 0x5b, 0x42, 0x0f, 0xc9, 0x88, 0x0d, 0xab, 0x76,
	0x34, 0x1a, 0x9c, 0x0c, 0xce, 0x76, 0x67, 0x5d, 0xbc, 0x54, 0x6c, 0xef, 0x69, 0x6d, 0xf1, 0x1e,
	0x4a, 0x4a, 0x9e, 0x19, 0x7b, 0x84, 0x10, 0x1b, 0x92, 0x43, 0xde, 0x8a, 0xe1, 0x9d, 0x35, 0xfe,
	0xb0, 0xb2, 0x36, 0x1e, 0xf1, 0xce, 0xf2, 0x1f, 0xd6, 0xf4, 0xe0, 0xf3, 0xfb, 0xe7, 0x6b, 0x8b,
	0x25, 0x3b, 0x22, 0x32, 0xee, 0x26, 0xaf, 0x47, 0x9b, 0x5f, 0xea, 0xc6, 0x2a, 0xb5, 0xdd, 0x14,
	0x5f, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x35, 0x2d, 0xd4, 0xcd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OnboardingDemoClient is the client API for OnboardingDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OnboardingDemoClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type onboardingDemoClient struct {
	cc *grpc.ClientConn
}

func NewOnboardingDemoClient(cc *grpc.ClientConn) OnboardingDemoClient {
	return &onboardingDemoClient{cc}
}

func (c *onboardingDemoClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.OnboardingDemo/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnboardingDemoServer is the server API for OnboardingDemo service.
type OnboardingDemoServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
}

func RegisterOnboardingDemoServer(s *grpc.Server, srv OnboardingDemoServer) {
	s.RegisterService(&_OnboardingDemo_serviceDesc, srv)
}

func _OnboardingDemo_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardingDemoServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.OnboardingDemo/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardingDemoServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _OnboardingDemo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.OnboardingDemo",
	HandlerType: (*OnboardingDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _OnboardingDemo_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "onboarding-demo/pkg/pb/service.proto",
}
